#Snake Game User Preferences
#Thu Apr 09 08:32:34 CST 2026
current.mode=crazy
normal.custom.board=\#330033
hard.obstacle=6
crazy.timeLimit=180
hard.speed=100
crazy.speedRate=10
normal.obstacle=0
hard.skin=classic
hard.timeLimit=150
normal.timed=false
crazy.custom.grid=\#33FF33
normal.speed=250
normal.speedRate=0
crazy.obstacle=20
normal.custom.grid=\#00FF66
crazy.speed=250
normal.skin=custom
hard.timed=false
crazy.skin=fresh
crazy.custom.board=\#330033
normal.timeLimit=180
crazy.timed=true
hard.speedRate=0
