#Snake Game User Preferences
#Sat Apr 11 17:18:48 CST 2026
hard.obstacle=20
crazy.timeLimit=180
hard.speed=100
normal.obstacle=0
normal.custom.obstacle=\#FF0000
normal.speed=250
normal.custom.grid=\#00FF66
crazy.speed=250
normal.skin=custom
crazy.skin=custom
crazy.custom.board=\#330033
normal.timeLimit=180
crazy.timed=true
current.mode=crazy
normal.custom.board=\#330033
crazy.custom.obstacle=\#0033FF
crazy.speedRate=10
hard.skin=classic
hard.timeLimit=30
normal.timed=false
crazy.custom.grid=\#33FF33
normal.speedRate=0
crazy.obstacle=20
hard.timed=false
hard.speedRate=0
